### ISSUE TITLE
How to save image 

### ISSUE THREAD

**Issue by akmal871026** [villekf/OMEGA#17]
Hi villekf/OMEGA,

I done run for OSEM and ACOSEM method. the image can view. 

but how to save image in my foder as dicom format?

**Comment by villekf** [comment]
You need to have the image processing toolbox, if you are using MATLAB, in order to save a DICOM image. For Octave, you need the dicom-package. The function [`saveImage`](https://github.com/villekf/OMEGA/blob/master/source/saveImage.m) or the built-in function [`dicomwrite`](https://www.mathworks.com/help/images/ref/dicomwrite.html) should be able to save the image(s). You can also try some other toolboxes like [Dicom toolbox](https://www.mathworks.com/matlabcentral/fileexchange/27941-dicom-toolbox).
