### ISSUE TITLE
PET system with more than 65536 detectors

### ISSUE THREAD

**Issue by Ompsda** [villekf/OMEGA#22]
Hi!

I'm attemting to use this software to reconstruct data comming from a PET system with more than 65536 detector? I don't know how to modify the code. Any suggestion please?

Thank you!

**Comment by villekf** [comment]
You may not have to modify anything anymore actually. Have you tried reconstructing the data? As long as you don't use the raw data format or implementation 1 with `options.precompute_lor = false`, everything should work fine nowadays. However, since I haven't been able to test this myself, I'm not 100% sure it will work.

In case it doesn't work, it would help to have at least the scanner specifics (i.e. the main-file).

**Comment by villekf** [comment]
I now tested this myself and using more than 65536 detectors works except in the following cases:

- Using the raw data format in OMEGA
- Loading ROOT data in MATLAB 2019a or later

The ROOT case will, however, be fixed in the next version.

**Comment by villekf** [comment]
More than 65536 detectors now works with ROOT data as well when using R2019a or later. 

If raw data support is needed, please open a new issue for that.
