### ISSUE TITLE
Projection images for the 3D walnut example

### ISSUE THREAD

**Issue by tbilloud** [villekf/OMEGA#27]
Hi!

I can't find the projection images in the link given in walnut_CT_main.m ... Or if it's in the .mat files, how to extract them ?

Sorry if it's a stupid question, I'm a newbie to matlab... 
Thanks for providing OMEGA, it's really useful !
Cheers,
Thomas

**Comment by villekf** [comment]
It is indeed contained in the mat-file. You can use either the `load` command or just double-click it in Matlab.

Since this is a Matlab-related question, I recommend you take a look at [getting started with Matlab](https://www.mathworks.com/help/matlab/getting-started-with-matlab.html).

I'm closing this issue since it's not OMEGA related.
