### ISSUE TITLE
Invenon PET data issue

### ISSUE THREAD

**Issue by June-phy** [villekf/OMEGA#29]
hello Ville, 

Greetings from USTC, China.,
My name is Qianxue, a Master student under the supervision of Prof.Dong Liu.
Currently we are trying to apply the well established PET softerware-OMEGA in our project, however, we face few questions, which we would like to get your help on this purpose. 

Q1: When I was attemping to use the Inveon PET data provided by the OMEGA, which obtained from [https://doi.org/10.5281/zenodo.3528056](https://doi.org/10.5281/zenodo.3528056).
I found some apparent ARTIFACTS in the sinogram. What's the reason lies behind it?
![576a046a123e1921d722379a6d01d14](https://user-images.githubusercontent.com/78997209/142392431-b02358cf-98b4-465e-a329-fee7daa40842.png)
Q2: I want to get more raw data to test on the OMEGA, but most of the data I get is in DICOM format. I was wondering whether this kind of data can be used to perform the reconstrucion. And where can I get more raw data?

Best wishes,
Qianxue

**Comment by villekf** [comment]
Hi Qianxue,

Glad to hear of your interest towards OMEGA. As for your questions:

1. The artifacts in the sinogram are caused by the lack of normalization correction. You can remove them by precorrecting the sinogram, but personally I tend to do the normalization correction during the reconstruction.
2. DICOM format data should be fine, if you can import it to Matlab/Octave. For Matlab, you need the image processing toolbox and use either [dicomread](https://www.mathworks.com/help/images/ref/dicomread.html) or [dicomreadVolume](https://www.mathworks.com/help/images/ref/dicomreadvolume.html). For Octave, there is the [DICOM](https://octave.sourceforge.io/dicom/) package. I have another list-mode dataset of a NEMA phantom in [Zenodo](https://zenodo.org/record/4646897), but that was also obtained from the Inveon PET scanner.

**Comment by June-phy** [comment]
Thanks for the prompt reply, I will try to figure it out. 
















At 2021-11-18 18:46:18, "villekf" ***@***.***> wrote:

Hi Qianxue,

Glad to hear of your interest towards OMEGA. As for your questions:

The artifacts in the sinogram are caused by the lack of normalization correction. You can remove them by precorrecting the sinogram, but personally I tend to do the normalization correction during the reconstruction.
DICOM format data should be fine, if you can import it to Matlab/Octave. For Matlab, you need the image processing toolbox and use either dicomread or dicomreadVolume. For Octave, there is the DICOM package. I have another list-mode dataset of a NEMA phantom in Zenodo, but that was also obtained from the Inveon PET scanner.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
