### ISSUE TITLE
main_PET.m issue

### ISSUE THREAD

**Issue by TingFeng-ZZJ** [villekf/OMEGA#37]
Dear villekf,
When I using main_PET.m for my own scanner and my own data ,it appears some mistakes.The command window as follow:
![image](https://user-images.githubusercontent.com/110451114/217820604-712bf237-71e4-43de-94a7-6aaf18025b9d.png)
My data format is contain the crystal number only:
![image](https://user-images.githubusercontent.com/110451114/217821139-bfb76aba-cec9-473d-a65f-82cc69a2db6a.png)
What can i do to handle this error?
Best wishes

**Comment by villekf** [comment]
I think the structure of your input data is incorrect. The `options.coincidences` should include the number of counts for each detector pair. I believe you have first detector number in the first column, number of counts in the second and third, and the second detector number in the fourth? If so, you should combine the counts in a matrix containing all possible detector pair combinations. If some combination has no counts, it should be zero. If not, then I'd need more information to help.

**Comment by villekf** [comment]
Just to add that alternatively you could also reconstruct only the detector pairs that have counts. In such a case you need to input coordinates for all those pairs and the number of counts. See [Custom detector coordinates and/or list mode reconstruction](https://github.com/villekf/OMEGA/wiki/Custom-detector-coordinates-and-or-list-mode-reconstruction) for details.

**Comment by TingFeng-ZZJ** [comment]
Thank you very much and now I know your means,I will try later.
Best wishes.

**Comment by TingFeng-ZZJ** [comment]
Dear villekf,
Can you tell me the list-mode data format that OMEGA support ? Such as the information does each column correspond to ? So that I can rearrange my data that OMEGA can reconstruction. And I want to ask you does OMEGA can support double layer PET  like this:
![image](https://user-images.githubusercontent.com/110451114/217986967-f7a02f44-cf5a-4c2b-8765-bba3404d2293.png)
Best wishes.

**Comment by villekf** [comment]
For list-mode reconstruction, you should have the x/y/z-coordinates of the detectors in `options.x/y/z`, respectively. The first column is the first detector, and the second column the second. The order of the detectors doesn't matter in PET though. Then `options.SinM` has the number of counts for that detector pair. In an event-by-event case it would be just one.

Dual-layer PET should actually be possible with the above manual reconstruction. However, the next release should have support for sinogram dual-layer reconstruction as well. Though since I'm doing CT stuff now, I'm not sure how well I will be able to test the PET part.

**Comment by TingFeng-ZZJ** [comment]
Dear professor,
Thank you for your careful reply.

I organize my data to the formation you said,like this :
![image](https://user-images.githubusercontent.com/110451114/218309167-85e32ad6-eec8-4c01-b7e4-a9312aeaa59b.png)
![image](https://user-images.githubusercontent.com/110451114/218309319-727a37ce-434b-422a-ad2b-6bfa63c48a5a.png)

But I can't set options.SinM in the main_PET.m funtion:
![image](https://user-images.githubusercontent.com/110451114/218309358-d439cc41-ced7-4856-88c9-7b1a732b6ef9.png)

And the same error appearance:
![image](https://user-images.githubusercontent.com/110451114/218309766-26e4cca0-61e0-42c3-a7ea-b4d5c6542511.png)

**Comment by villekf** [comment]
Did you input the coordinates to `options.coincidences`? They should be input to `options.x/y/z`. 

Why you can't set the `options.SinM`? From your screenshot, it seems you could freely input any data/value to it. However, since you've used the `options.coincidences` so far, I think it should be fine as well as long as you keep using raw data (this is not, however, necessary).

Have you looked at [Inveon_PET_main_listmode_example.m](https://github.com/villekf/OMEGA/blob/master/Inveon_PET_main_listmode_example.m)? It contains an example of list-mode reconstruction. I recommend using similar settings.

**Comment by TingFeng-ZZJ** [comment]
OK,Thank you very much.
